#!/bin/sh
HAYSTACK_GIT_ASKPASS_PIPE=`mktemp`
ELECTRON_RUN_AS_NODE="1" HAYSTACK_GIT_ASKPASS_PIPE="$HAYSTACK_GIT_ASKPASS_PIPE" HAYSTACK_GIT_ASKPASS_TYPE="https" "$HAYSTACK_GIT_ASKPASS_NODE" "$HAYSTACK_GIT_ASKPASS_MAIN" $HAYSTACK_GIT_ASKPASS_EXTRA_ARGS $*
cat $HAYSTACK_GIT_ASKPASS_PIPE
rm $HAYSTACK_GIT_ASKPASS_PIPE
